### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by fmichonneau**
@LunaSare here is the updated template that fixes the issues about not having a specific class for warnings. Once you merge this, you can regenerate the lesson locally and push the changes to the repo.

### CODE REVIEW

**Comment by LunaSare** [comment]
Thank you, this is so useful!

**Comment by LunaSare** [comment]
Ah, so, the warning class is working great, and I am able to use it "manually" on an md file. However, rendering from an Rmd file will still assign the error class to a warning. Not sure how complicated adding this functionality would be 😬??

**Comment by fmichonneau** [comment]
I think I figured out the issue! 

Do you have the `emo` package installed? by putting `library("emo")` at the top of the `../bin/chunk-options.R` file, I didn't have it installed and the sourcing of the code in this file stopped. It means that the hook functions that control the appearance of the blocks were not evaluated. After installing the package I got it to work (the automatically generated files had the proper warning styling).

**Comment by LunaSare** [comment]
Ah! Thanks for looking into this! Well, it was obviously my fault. I do have `emo` installed, but something else in my code was definitely stopping the evaluations, because the warnings are rendering correctly after I did some edits on other parts of the code. I will keep that in mind from now on. Thanks so much for your help again!

**Pull request merged**
